namespace BusinessPartnerPortal.Api.Domain;

public sealed class Department { public Guid Id { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; }
public sealed class User { public Guid Id { get; set; } public string FullName { get; set; } = ""; public string Email { get; set; } = ""; public string? PasswordHash { get; set; } public string UserType { get; set; } = "VENDOR"; public Guid? DepartmentId { get; set; } public bool IsSuperAdmin { get; set; } public bool IsActive { get; set; } = true; public bool MfaEnabled { get; set; } public int FailedLoginAttempts { get; set; } public DateTimeOffset? LockoutUntil { get; set; } public DateTimeOffset? LastLoginAt { get; set; } public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset UpdatedAt { get; set; } }
public sealed class Role { public Guid Id { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public bool IsActive { get; set; } = true; }
public sealed class UserRole { public Guid UserId { get; set; } public Guid RoleId { get; set; } }
public sealed class Feature { public Guid Id { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string? RoutePath { get; set; } }
public sealed class Permission { public Guid Id { get; set; } public Guid? FeatureId { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; }
public sealed class RolePermission { public Guid RoleId { get; set; } public Guid PermissionId { get; set; } }
public sealed class UserPermissionOverride { public Guid UserId { get; set; } public Guid PermissionId { get; set; } public bool IsAllowed { get; set; } }
public sealed class Vendor { public Guid Id { get; set; } public string VendorCode { get; set; } = ""; public string VendorName { get; set; } = ""; public string? OracleVendorId { get; set; } public bool IsActive { get; set; } = true; }
public sealed class VendorUser { public Guid VendorId { get; set; } public Guid UserId { get; set; } public bool IsPrimary { get; set; } public bool IsActive { get; set; } = true; }
public sealed class PurchaseOrder { public Guid Id { get; set; } public Guid VendorId { get; set; } public string PoNumber { get; set; } = ""; public DateOnly? PoDate { get; set; } public string CurrencyCode { get; set; } = "PKR"; public decimal TotalAmount { get; set; } public decimal RemainingAmount { get; set; } public string Status { get; set; } = "OPEN"; }
public sealed class Grn { public Guid Id { get; set; } public Guid PurchaseOrderId { get; set; } public string GrnNumber { get; set; } = ""; public DateOnly? GrnDate { get; set; } public string Status { get; set; } = "OPEN"; public string QcStatus { get; set; } = "NOT_REQUIRED"; }
public sealed class Invoice { public Guid Id { get; set; } public Guid VendorId { get; set; } public string InvoiceNumber { get; set; } = ""; public DateOnly? InvoiceDate { get; set; } public decimal InvoiceAmount { get; set; } public string CurrencyCode { get; set; } = "PKR"; public string? PoNumber { get; set; } public string? GrnNumbers { get; set; } public string InvoiceType { get; set; } = "GOODS"; public string Status { get; set; } = "DRAFT"; public string IntegrationStatus { get; set; } = "NOT_STARTED"; public string? OracleInvoiceId { get; set; } public DateTimeOffset? SubmissionDate { get; set; } public string? Remarks { get; set; } public Guid CreatedBy { get; set; } public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset UpdatedAt { get; set; } public DateTimeOffset? DeletedAt { get; set; } }
public sealed class InvoiceGrn { public Guid InvoiceId { get; set; } public Guid GrnId { get; set; } }
public sealed class Document { public Guid Id { get; set; } public Guid InvoiceId { get; set; } public string DocumentType { get; set; } = "INVOICE"; public string OriginalFileName { get; set; } = ""; public string ContentType { get; set; } = ""; public string? FileExtension { get; set; } public long FileSize { get; set; } public string FileHashSha256 { get; set; } = ""; public byte[] FileContent { get; set; } = []; public Guid UploadedBy { get; set; } public DateTimeOffset UploadedAt { get; set; } }
public sealed class InvoiceStatusHistory { public long Id { get; set; } public Guid InvoiceId { get; set; } public string? OldStatus { get; set; } public string NewStatus { get; set; } = ""; public string? Remarks { get; set; } public string Source { get; set; } = "PORTAL"; public Guid? ChangedBy { get; set; } public DateTimeOffset ChangedAt { get; set; } public Guid? CorrelationId { get; set; } }
public sealed class Payment { public Guid Id { get; set; } public Guid InvoiceId { get; set; } public string? PaymentReference { get; set; } public DateOnly? PaymentDate { get; set; } public decimal Amount { get; set; } public string Status { get; set; } = "PENDING"; }
