using BusinessPartnerPortal.Api.Common;using BusinessPartnerPortal.Api.Data;using BusinessPartnerPortal.Api.Domain;using BusinessPartnerPortal.Api.Security;using Microsoft.AspNetCore.Identity;using Microsoft.EntityFrameworkCore;
namespace BusinessPartnerPortal.Api.Features.Admin;
public static class AdminEndpoints{
 public static IEndpointRouteBuilder MapAdminEndpoints(this IEndpointRouteBuilder app){var g=app.MapGroup("/api/v1/admin").RequireAuthorization().WithTags("Admin");
  g.MapGet("/roles",async(CurrentUser current,AppDbContext db,CancellationToken ct)=>{DemandAdmin(current);return Results.Ok(await db.Roles.Where(x=>x.IsActive).OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Code,x.Name}).ToListAsync(ct));});
  g.MapGet("/permissions",async(CurrentUser current,AppDbContext db,CancellationToken ct)=>{DemandAdmin(current);return Results.Ok(await db.Permissions.OrderBy(x=>x.Code).Select(x=>new{x.Id,x.Code,x.Name}).ToListAsync(ct));});
  g.MapGet("/roles/{roleId:guid}/permissions",async(Guid roleId,CurrentUser current,AppDbContext db,CancellationToken ct)=>{DemandAdmin(current);var exists=await db.Roles.AnyAsync(x=>x.Id==roleId,ct);if(!exists)throw new ApiException(404,"Role not found.");var ids=await db.RolePermissions.Where(x=>x.RoleId==roleId).Select(x=>x.PermissionId).ToListAsync(ct);return Results.Ok(ids);});
  g.MapPut("/roles/{roleId:guid}/permissions",async(Guid roleId,RolePermissionsRequest req,CurrentUser current,AppDbContext db,CancellationToken ct)=>{DemandAdmin(current);var role=await db.Roles.FirstOrDefaultAsync(x=>x.Id==roleId,ct)??throw new ApiException(404,"Role not found.");if(role.Code=="ADMIN")throw new ApiException(409,"Administrator permissions are implicitly unrestricted and cannot be reduced here.");var valid=await db.Permissions.Where(x=>req.PermissionIds.Contains(x.Id)).Select(x=>x.Id).ToListAsync(ct);var old=await db.RolePermissions.Where(x=>x.RoleId==roleId).ToListAsync(ct);db.RolePermissions.RemoveRange(old);foreach(var id in valid)db.RolePermissions.Add(new RolePermission{RoleId=roleId,PermissionId=id});await db.SaveChangesAsync(ct);await Audit(db,current.UserId,"ROLE_PERMISSIONS_UPDATED","Role",roleId,ct);return Results.Ok(new{roleId,permissionIds=valid});});
  g.MapGet("/system",(CurrentUser current,IConfiguration cfg)=>{DemandAdmin(current);return Results.Ok(new{environment=cfg["APP_ENV"]??"Development",oracleConfigured=!string.IsNullOrWhiteSpace(cfg["ORACLE_HOST"])&&!string.IsNullOrWhiteSpace(cfg["ORACLE_SERVICE_NAME"]),oracleInvoicePostConfigured=!string.IsNullOrWhiteSpace(cfg["ORACLE_INVOICE_POST_URL"]),smtpEnabled=bool.TryParse(cfg["SMTP_ENABLED"],out var smtp)&&smtp,maxUploadSizeMb=cfg["MAX_UPLOAD_SIZE_MB"]??"10",dataRetentionDays=cfg["DATA_RETENTION_DAYS"]??"0"});});
  g.MapGet("/users",async(CurrentUser current,AppDbContext db,CancellationToken ct)=>{DemandAdmin(current);var users=await db.Users.OrderBy(x=>x.FullName).ToListAsync(ct);var result=new List<object>();foreach(var u in users){var roles=await(from ur in db.UserRoles join r in db.Roles on ur.RoleId equals r.Id where ur.UserId==u.Id select r.Code).ToListAsync(ct);result.Add(new{u.Id,u.FullName,u.Email,u.UserType,u.IsActive,u.IsSuperAdmin,u.LastLoginAt,roles});}return Results.Ok(result);});
  g.MapPost("/users",async(UserMutationRequest req,CurrentUser current,AppDbContext db,CancellationToken ct)=>{DemandAdmin(current);if(string.IsNullOrWhiteSpace(req.Password)||req.Password.Length<10)throw new ApiException(400,"Temporary password must be at least 10 characters.");var email=req.Email.Trim().ToLowerInvariant();if(await db.Users.AnyAsync(x=>x.Email.ToLower()==email,ct))throw new ApiException(409,"A user with this email already exists.");var user=new User{Id=Guid.NewGuid(),FullName=req.FullName.Trim(),Email=email,UserType=req.UserType.Trim().ToUpperInvariant(),IsActive=req.IsActive,IsSuperAdmin=req.IsSuperAdmin,CreatedAt=DateTimeOffset.UtcNow,UpdatedAt=DateTimeOffset.UtcNow};user.PasswordHash=new PasswordHasher<User>().HashPassword(user,req.Password);db.Users.Add(user);await db.SaveChangesAsync(ct);await ReplaceRoles(db,user.Id,req.RoleCodes,ct);await Audit(db,current.UserId,"USER_CREATED","User",user.Id,ct);return Results.Ok(new{id=user.Id});});
  g.MapPut("/users/{userId:guid}",async(Guid userId,UserMutationRequest req,CurrentUser current,AppDbContext db,CancellationToken ct)=>{DemandAdmin(current);var user=await db.Users.FirstOrDefaultAsync(x=>x.Id==userId,ct)??throw new ApiException(404,"User not found.");var email=req.Email.Trim().ToLowerInvariant();if(await db.Users.AnyAsync(x=>x.Id!=userId&&x.Email.ToLower()==email,ct))throw new ApiException(409,"Another user already uses this email.");user.FullName=req.FullName.Trim();user.Email=email;user.UserType=req.UserType.Trim().ToUpperInvariant();user.IsActive=req.IsActive;user.IsSuperAdmin=req.IsSuperAdmin;user.UpdatedAt=DateTimeOffset.UtcNow;if(!string.IsNullOrWhiteSpace(req.Password))user.PasswordHash=new PasswordHasher<User>().HashPassword(user,req.Password);await db.SaveChangesAsync(ct);await ReplaceRoles(db,user.Id,req.RoleCodes,ct);await Audit(db,current.UserId,"USER_UPDATED","User",user.Id,ct);return Results.Ok(new{id=user.Id});});
  g.MapGet("/audit",async(CurrentUser current,AppDbContext db,CancellationToken ct)=>{DemandAdmin(current);var conn=db.Database.GetDbConnection();if(conn.State!=System.Data.ConnectionState.Open)await conn.OpenAsync(ct);await using var cmd=conn.CreateCommand();cmd.CommandText="SELECT id,user_id,action,entity_type,entity_id,correlation_id,created_at FROM audit.audit_logs ORDER BY created_at DESC LIMIT 500";var list=new List<object>();await using var rd=await cmd.ExecuteReaderAsync(ct);while(await rd.ReadAsync(ct))list.Add(new{id=rd.GetInt64(0),userId=rd.IsDBNull(1)?null:rd.GetGuid(1).ToString(),action=rd.GetString(2),entityType=rd.GetString(3),entityId=rd.IsDBNull(4)?null:rd.GetGuid(4).ToString(),correlationId=rd.IsDBNull(5)?null:rd.GetGuid(5).ToString(),createdAt=rd.GetFieldValue<DateTimeOffset>(6)});return Results.Ok(list);});return app;}
 static void DemandAdmin(CurrentUser current){if(!current.IsAdmin)throw new ApiException(403,"Administrator access is required.");}
 static async Task ReplaceRoles(AppDbContext db,Guid userId,List<string>? codes,CancellationToken ct){var wanted=(codes??[]).Select(x=>x.Trim().ToUpperInvariant()).Distinct().ToList();var roleIds=await db.Roles.Where(x=>wanted.Contains(x.Code)).Select(x=>x.Id).ToListAsync(ct);var existing=await db.UserRoles.Where(x=>x.UserId==userId).ToListAsync(ct);db.UserRoles.RemoveRange(existing);foreach(var rid in roleIds)db.UserRoles.Add(new UserRole{UserId=userId,RoleId=rid});await db.SaveChangesAsync(ct);}
 static Task<int> Audit(AppDbContext db,Guid userId,string action,string entityType,Guid entityId,CancellationToken ct)=>db.Database.ExecuteSqlInterpolatedAsync($"INSERT INTO audit.audit_logs(user_id,action,entity_type,entity_id,created_at) VALUES ({userId},{action},{entityType},{entityId},now())",ct);
 public sealed record UserMutationRequest(string FullName,string Email,string UserType,List<string>? RoleCodes,string? Password,bool IsActive=true,bool IsSuperAdmin=false); public sealed record RolePermissionsRequest(List<Guid> PermissionIds);
}
