using System.Security.Cryptography;using BusinessPartnerPortal.Api.Common;using BusinessPartnerPortal.Api.Data;using BusinessPartnerPortal.Api.Domain;using BusinessPartnerPortal.Api.Oracle;using BusinessPartnerPortal.Api.Services;using Microsoft.AspNetCore.Identity;using Microsoft.EntityFrameworkCore;
namespace BusinessPartnerPortal.Api.Features.Registration;
public static class RegistrationEndpoints{
 public static IEndpointRouteBuilder MapRegistrationEndpoints(this IEndpointRouteBuilder app){var g=app.MapGroup("/api/v1/registration/vendor").WithTags("Vendor Registration");
  g.MapPost("/start",async(StartRequest req,OracleService oracle,RegistrationOtpStore store,EmailOtpSender sender,IWebHostEnvironment env,AppDbContext db,CancellationToken ct)=>{if(string.IsNullOrWhiteSpace(req.SupplierNumber)||string.IsNullOrWhiteSpace(req.VendorName)||string.IsNullOrWhiteSpace(req.Email))throw new ApiException(400,"Supplier number, vendor name and registered email are required.");var s=await oracle.GetSupplierByNumberAsync(req.SupplierNumber,ct)??throw new ApiException(404,"Supplier was not found in Oracle EBS.");if(!Norm(s.VendorName).Equals(Norm(req.VendorName)))throw new ApiException(400,"Vendor name does not match the Oracle supplier record.");if(string.IsNullOrWhiteSpace(s.Email))throw new ApiException(409,"Oracle supplier does not have a registered email. Contact Supply Chain.");if(!s.Email.Equals(req.Email.Trim(),StringComparison.OrdinalIgnoreCase))throw new ApiException(400,"Email does not match the Oracle registered supplier email.");if(await db.Users.AnyAsync(x=>x.Email.ToLower()==req.Email.Trim().ToLower(),ct))throw new ApiException(409,"A portal account already exists for this email.");var otp=RandomNumberGenerator.GetInt32(100000,999999).ToString();var c=store.Create(s.SupplierNumber,s.VendorId,s.VendorName,s.Email,otp);await sender.SendAsync(s.Email,otp,ct);return Results.Ok(new{challengeId=c.Id,maskedEmail=Mask(s.Email),devOtp=env.IsDevelopment()&&!(bool.TryParse(app.ServiceProvider.GetRequiredService<IConfiguration>()["SMTP_ENABLED"],out var enabled)&&enabled)?otp:null});}).AllowAnonymous();
  g.MapPost("/complete",async(CompleteRequest req,RegistrationOtpStore store,AppDbContext db,CancellationToken ct)=>{if(req.Password!=req.ConfirmPassword)throw new ApiException(400,"Passwords do not match.");if(req.Password.Length<10)throw new ApiException(400,"Password must be at least 10 characters.");var c=store.Get(req.ChallengeId)??throw new ApiException(400,"Registration challenge is invalid or expired.");if(c.ExpiresAt<DateTimeOffset.UtcNow){store.Remove(c.Id);throw new ApiException(400,"OTP expired. Start registration again.");}if(!CryptographicOperations.FixedTimeEquals(System.Text.Encoding.UTF8.GetBytes(c.Otp),System.Text.Encoding.UTF8.GetBytes(req.Otp.Trim())))throw new ApiException(400,"Invalid OTP.");await using var tx=await db.Database.BeginTransactionAsync(ct);var vendor=await db.Vendors.FirstOrDefaultAsync(x=>x.OracleVendorId==c.VendorId,ct);if(vendor is null){vendor=new Vendor{Id=Guid.NewGuid(),VendorCode="ORACLE-"+c.SupplierNumber,VendorName=c.VendorName,OracleVendorId=c.VendorId,IsActive=true};db.Vendors.Add(vendor);}var user=new User{Id=Guid.NewGuid(),FullName=req.FullName.Trim(),Email=c.Email,UserType="VENDOR",IsActive=true,CreatedAt=DateTimeOffset.UtcNow,UpdatedAt=DateTimeOffset.UtcNow};user.PasswordHash=new PasswordHasher<User>().HashPassword(user,req.Password);db.Users.Add(user);var role=await db.Roles.FirstAsync(x=>x.Code=="VENDOR",ct);db.UserRoles.Add(new UserRole{UserId=user.Id,RoleId=role.Id});db.VendorUsers.Add(new VendorUser{VendorId=vendor.Id,UserId=user.Id,IsPrimary=true,IsActive=true});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);store.Remove(c.Id);return Results.Ok(new{registered=true,email=c.Email,oracleVendorId=c.VendorId});}).AllowAnonymous();return app;}
 static string Norm(string x)=>new string(x.Trim().ToUpperInvariant().Where(char.IsLetterOrDigit).ToArray());static string Mask(string email){var p=email.Split('@');if(p.Length!=2)return"***";var n=p[0];return(n.Length<=2?"**":n[..2]+new string('*',Math.Max(2,n.Length-2)))+"@"+p[1];}
 public sealed record StartRequest(string SupplierNumber,string VendorName,string Email);public sealed record CompleteRequest(Guid ChallengeId,string Otp,string FullName,string Password,string ConfirmPassword);
}
