using Oracle.ManagedDataAccess.Client;using System.Data;
namespace BusinessPartnerPortal.Api.Oracle;
public sealed class OracleService(OracleOptions options,ILogger<OracleService> logger){
 async Task<OracleConnection> Open(CancellationToken ct){var c=new OracleConnection(options.ConnectionString);await c.OpenAsync(ct);return c;}
 public async Task<bool> TestConnectivityAsync(CancellationToken ct){await using var c=await Open(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT 1 FROM DUAL";return Convert.ToInt32(await cmd.ExecuteScalarAsync(ct))==1;}
 public async Task<OracleSupplierDto?> GetSupplierByVendorIdAsync(decimal vendorId,CancellationToken ct){await using var c=await Open(ct);await using var cmd=c.CreateCommand();cmd.BindByName=true;cmd.CommandText="SELECT * FROM APPS.PORTAL_SUPPLIERS_V WHERE VENDOR_ID=:vendorId AND ROWNUM=1";cmd.Parameters.Add("vendorId",OracleDbType.Decimal).Value=vendorId;var r=await Read(cmd,ct);return r.Count==0?null:MapSupplier(r[0]);}
 public async Task<OracleSupplierDto?> GetSupplierByNumberAsync(string supplierNumber,CancellationToken ct){await using var c=await Open(ct);await using var cmd=c.CreateCommand();cmd.BindByName=true;cmd.CommandText="SELECT * FROM APPS.PORTAL_SUPPLIERS_V WHERE TRIM(CAST(SUPPLIER_NUMBER AS VARCHAR2(100)))=:supplierNumber AND ROWNUM=1";cmd.Parameters.Add("supplierNumber",OracleDbType.Varchar2).Value=supplierNumber.Trim();var r=await Read(cmd,ct);return r.Count==0?null:MapSupplier(r[0]);}
 public async Task<List<OracleSupplierDto>> GetSuppliersAsync(CancellationToken ct){await using var c=await Open(ct);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT * FROM APPS.PORTAL_SUPPLIERS_V WHERE ROWNUM<=500 ORDER BY VENDOR_NAME";return (await Read(cmd,ct)).Select(MapSupplier).ToList();}
 public async Task<List<OraclePoGrnDto>> GetPoGrnsAsync(decimal vendorId,string? poNumber,CancellationToken ct){await using var c=await Open(ct);await using var cmd=c.CreateCommand();cmd.BindByName=true;cmd.CommandText="SELECT * FROM APPS.PORTAL_PO_GRN_V WHERE VENDOR_ID=:vendorId"+(string.IsNullOrWhiteSpace(poNumber)?"":" AND TRIM(CAST(PO_NUMBER AS VARCHAR2(100)))=:poNumber")+" ORDER BY PO_NUMBER DESC, RECEIPT_DATE DESC NULLS LAST";cmd.Parameters.Add("vendorId",OracleDbType.Decimal).Value=vendorId;if(!string.IsNullOrWhiteSpace(poNumber))cmd.Parameters.Add("poNumber",OracleDbType.Varchar2).Value=poNumber;return(await Read(cmd,ct)).Select(MapPoGrn).ToList();}
 public async Task<List<OracleInvoiceDto>> GetInvoicesAsync(decimal vendorId,CancellationToken ct){await using var c=await Open(ct);await using var cmd=c.CreateCommand();cmd.BindByName=true;cmd.CommandText="SELECT * FROM APPS.PORTAL_INVOICES_V WHERE VENDOR_ID=:vendorId ORDER BY INVOICE_DATE DESC NULLS LAST";cmd.Parameters.Add("vendorId",OracleDbType.Decimal).Value=vendorId;return(await Read(cmd,ct)).Select(MapInvoice).ToList();}
 async Task<List<Dictionary<string,object?>>> Read(OracleCommand cmd,CancellationToken ct){try{var list=new List<Dictionary<string,object?>>();await using var rd=await cmd.ExecuteReaderAsync(ct);while(await rd.ReadAsync(ct)){var d=new Dictionary<string,object?>(StringComparer.OrdinalIgnoreCase);for(var i=0;i<rd.FieldCount;i++)d[rd.GetName(i)]=rd.IsDBNull(i)?null:rd.GetValue(i);list.Add(d);}return list;}catch(OracleException ex){logger.LogWarning(ex,"Oracle query failed. OracleError={Number}",ex.Number);throw;}}
 static string S(Dictionary<string,object?>d,params string[]n){foreach(var x in n)if(d.TryGetValue(x,out var v)&&v is not null)return Convert.ToString(v)??"";return"";}static decimal? N(Dictionary<string,object?>d,params string[]n){var s=S(d,n);return decimal.TryParse(s,out var x)?x:null;}static DateTime? D(Dictionary<string,object?>d,params string[]n){foreach(var x in n)if(d.TryGetValue(x,out var v)&&v is DateTime dt)return dt;return DateTime.TryParse(S(d,n),out var z)?z:null;}
 static OracleSupplierDto MapSupplier(Dictionary<string,object?>d)=>new(S(d,"VENDOR_ID"),S(d,"SUPPLIER_NUMBER"),S(d,"VENDOR_NAME"),S(d,"VENDOR_SITE_ID"),S(d,"VENDOR_SITE_CODE"),S(d,"ORG_ID"),S(d,"OPERATING_UNIT"),S(d,"EMAIL_ADDRESS","EMAIL","VENDOR_EMAIL"),S(d,"PHONE","PHONE_NUMBER"),S(d,"TAX_REGISTRATION_NUMBER","NTN","TAX_NUMBER"));
 static OraclePoGrnDto MapPoGrn(Dictionary<string,object?>d)=>new(S(d,"PO_HEADER_ID"),S(d,"PO_NUMBER"),S(d,"PO_TYPE"),S(d,"PO_STATUS"),S(d,"INSPECTION_STATUS"),S(d,"VENDOR_ID"),S(d,"VENDOR_NAME"),S(d,"VENDOR_SITE_CODE"),S(d,"PO_LINE_ID"),S(d,"PO_LINE_NUM"),S(d,"ITEM_CODE"),S(d,"ITEM_DESCRIPTION"),S(d,"UOM"),N(d,"PO_QUANTITY"),N(d,"UNIT_PRICE"),N(d,"PO_LINE_AMOUNT"),N(d,"ORDERED_QUANTITY"),N(d,"RECEIVED_QUANTITY"),N(d,"BILLED_QUANTITY"),N(d,"CANCELLED_QUANTITY"),N(d,"QUANTITY_AVAILABLE_TO_INVOICE"),S(d,"GRN_NUMBER"),N(d,"GRN_RECEIVED_QUANTITY"),D(d,"RECEIPT_DATE"),S(d,"CURRENCY_CODE"),D(d,"PO_CREATION_DATE"),D(d,"PO_APPROVED_DATE"));
 static OracleInvoiceDto MapInvoice(Dictionary<string,object?>d)=>new(S(d,"VENDOR_ID"),S(d,"SUPPLIER_NUMBER"),S(d,"VENDOR_NAME"),S(d,"INVOICE_NUM","INVOICE_NUMBER"),D(d,"INVOICE_DATE"),N(d,"INVOICE_AMOUNT")??0,N(d,"AMOUNT_PAID"),N(d,"OUTSTANDING_AMOUNT"),S(d,"PAYMENT_STATUS_FLAG"),S(d,"PAYMENT_STATUS"),S(d,"APPROVAL_STATUS"),S(d,"PO_NUMBER"),S(d,"GRN_NUMBER"),D(d,"RECEIPT_DATE"));
}
